Hounslow-Connect/admin

- aws/cloudformation.py
https://trello.com/c/b0uq24cc
Updated deploy scripts
NA
NA
> Change project name in cloudformation

- src/components/SpreadsheetImportErrors.vue
- src/components/SpreadsheetImportForm.vue
- src/router.js
- src/views/organisations/Import.vue
- src/views/organisations/Index.vue
https://app.clubhouse.io/ayup-digital-ltd/story/83/page-for-organisations-csv-import-tool
A new page needs adding to the admin web app which will allow super admins to upload a CSV containing new organisations.
NA
NA
> Added Organisation import view

- src/components/SpreadsheetImportErrors.vue
- src/router.js
- src/views/services/Import.vue
- src/views/services/Index.vue
https://app.clubhouse.io/ayup-digital-ltd/story/84/page-for-services-csv-import-tool
Created view for Services xls/xlsx import
Requires https://github.com/One-Hounslow-Connect/api/pull/44
NA
> Added service import view

- src/views/services/Import.vue
https://app.clubhouse.io/ayup-digital-ltd/story/270/incorrect-url-for-example-csv-on-service-import-page
Typo in download link URL
NA
NA
> Fixed services import example link

- src/components/CkOrganisationDetails.vue
- src/views/organisations/Create.vue
- src/views/services/Create.vue
- src/views/services/forms/EligibilityTab.vue
https://app.clubhouse.io/ayup-digital-ltd/story/185/add-taxonomies-to-organisations
Added Organisation taxonomies to create and show views
NA
NA
> Added Organisation categories to create and show views

- src/views/services/Create.vue
- src/views/services/Edit.vue
- src/views/services/forms/AdditionalInfoTab.vue
https://app.clubhouse.io/ayup-digital-ltd/story/180/remove-social-media-support-for-services
- Removed social media input from create Service
- Removed social media input from update Service
- Removed social media listings from show Service
- Removed social media from update requests for Service
NA
NA
> Removed Social Media from view, update and create service

- src/views/locations/forms/LocationForm.vue
https://app.clubhouse.io/ayup-digital-ltd/story/321/service-creation-bug-with-invalid-addresses
Added error message to handle address not found errors to Locations create view. Not added to update view as this is managed via an update request.
NA
NA
> Added adress not found error message to Location create view

- src/views/services/Create.vue
https://app.clubhouse.io/ayup-digital-ltd/story/694/adding-a-new-service-as-an-organisation-admin-fails
Updated response to create service for organisation admin role
NA
NA
> Updated response to create submit based on role

- src/views/update-requests/show/ServiceDetails.vue
https://app.clubhouse.io/ayup-digital-ltd/story/686/viewing-an-update-request-for-a-new-service-doesn-t-work
The lack of an origin object on a new service was causing the service details view on update request to fail. Strategies to cope with a possible missing origin object are implemented.
NA
NA
> ServiceDetails handles lack of origin object better

- src/App.vue
- src/router.js
- src/views/Dashboard.vue
- src/views/help/Index.vue
- src/views/help/components/VideoIframe.vue
https://app.clubhouse.io/ayup-digital-ltd/story/735/update-dashboard-to-include-youtube-playlist-help-page
- Added Help view
- Added video iframe component that will resize to space allowed
- Added links and menu item
NA
NA
> Added help page with menu and links

- .nvmrc
- .travis.yml
- aws/cloudformation.py
- src/views/register/forms/DetailsTab.vue
- src/views/register/new/Organisation.vue
https://app.shortcut.com/ayup-digital-ltd/story/1014/update-admin-app-to-be-configured-on-the-new-domain-name
- Create S3 webhosting bucket to redirect old domain to new domain
- Create Cloudfront distribution to pass requests to S3 redirect bucket
- Update references to old domain in codebase
> Hounslow sc 1014 update admin app to be configured on the

- src/components/Gov/GovFooter.vue
- src/main.js
- src/views/Dashboard.vue
- src/views/auth/Login.vue
- src/views/register/Completed.vue
- src/views/register/forms/AdditionalInfoTab.vue
- src/views/services/Create.vue
- src/views/services/PreCreate.vue
- src/views/services/forms/AdditionalInfoTab.vue
- src/views/services/forms/DetailsTab.vue
- src/views/services/forms/ReferralTab.vue
- src/views/services/forms/TaxonomiesTab.vue
- src/views/users/Create.vue
https://app.shortcut.com/ayup-digital-ltd/story/1023/update-the-email-address-in-the-admin-app-footer
- Set global computed property contactEmail from environment variable VUE_APP_CONTACT_EMAIL
- Set global computed property sessionMinutes from environment variable VUE_APP_SESSION_TIMEOUT
- Update all uses of contact email to use computed property instead of hardcoded email
- Update all usee of session timeout to use computed property
> Pull contact email from environment variable

- src/views/events/Create.vue
- src/views/events/Edit.vue
- src/views/events/forms/EventForm.vue
- src/views/events/inputs/EventHomepageInput.vue
- src/views/events/show/EventDetails.vue
https://app.shortcut.com/ayup-digital-ltd/story/1942/manage-featured-events-on-homepage-must
- Admin UI components to support homepage flag on organisation events
> Hounslow sc 1942 manage featured events on homepage must

- src/views/events/Create.vue
- src/views/events/Edit.vue
- src/views/events/forms/DetailsTab.vue
- src/views/events/forms/TaxonomiesTab.vue
- src/views/events/show/EventDetails.vue
https://app.shortcut.com/ayup-digital-ltd/story/2004/create-admin-ui-for-events-taxonomies
- Updated event edit view to use tabs
- Added current form to details tab
- Added new taxonomy tab
> Added taxonomies tab for events

- src/views/events/Create.vue
- src/views/events/Edit.vue
- src/views/events/Index.vue
- src/views/events/forms/DetailsTab.vue
https://app.shortcut.com/ayup-digital-ltd/story/1995/events-kitchen-sink
- Requested language and UI fixes
> Minor UI fixes

- src/router.js
- src/views/admin/index/Collections.vue
- src/views/admin/index/collections/Categories.vue
- src/views/admin/index/collections/CollectionListItem.vue
- src/views/admin/index/collections/Events.vue
- src/views/collections/events/Create.vue
- src/views/collections/events/Edit.vue
- src/views/collections/events/forms/CollectionForm.vue
https://app.shortcut.com/ayup-digital-ltd/story/2005/create-admin-ui-for-event-collections
- Added taxonomies tab to event edit view
- Allow event to be assigned taxonomies as per services
> Added event collection UI

- src/views/events/show/EventDetails.vue
- src/views/update-requests/Index.vue
- src/views/update-requests/Show.vue
- src/views/update-requests/show/OrganisationEventDetails.vue
https://app.shortcut.com/ayup-digital-ltd/story/2084/bug-update-request-invalid-type-on-event-update
- Much of the organisation event update request admin was in fact missing, so completed this
> Fixed organisation event update request

- src/components/Ck/CkLocationInput.vue
- src/views/events/Create.vue
- src/views/events/show/EventDetails.vue
Reverts Hounslow-Connect/admin#54
> Revert "Fixed syncing of location id and passing accessible toilet prop in ev…"

- src/components/Ck/CkLocationInput.vue
- src/views/events/Create.vue
- src/views/events/show/EventDetails.vue
https://app.shortcut.com/ayup-digital-ltd/story/2237/accessible-toilet-validation-error
- Added accessible toilet prop to event details tab
- sync location id when on create event view
> Hounslow sc 2237 accessible toilet validation error

- src/views/services/Import.vue
https://app.shortcut.com/ayup-digital-ltd/story/274/update-validation-on-services-import-to-flag-when-an-organisation-id-supplied-doesn-t-exist
- Added bad organisation id error to feedback from services import
> Added organisation error to service import feedback

- public/index.html
- src/App.vue
https://app.shortcut.com/ayup-digital-ltd/story/1813/update-admin-ui-app-so-that-it-s-not-indexed-by-google
- Added meta tag robots noindex
> Added robots noindex meta tag

- src/views/update-requests/show/ServiceDetails.vue
https://app.shortcut.com/ayup-digital-ltd/story/2549/bug-update-request-issue-with-new-service
- Added comment to allow creation of PR to trigger build
> Hounslow sc 2549 bug update request issue with new service

- src/views/services/Create.vue
https://app.shortcut.com/ayup-digital-ltd/story/2557/update-the-content-on-the-service-creation-page
- Updated service creation UI
> Hide the service creation instructions when the form is submitted
